### ISSUE TITLE
Set title

### ISSUE THREAD

**Issue by Preen** [nomad/houston#140]
As of iOS 8.2 you have the option to pass an title. I cant see that this is supported by Houston?

http://stackoverflow.com/questions/40647061/bold-or-other-formatting-in-ios-push-notification

**Comment by markquezada** [comment]
The `alert` key as implemented in Houston will pass-through any data to be serialized and sent to the Apple push notification service. I believe this is purposeful as there are many valid values for this field as per [Apple's push notification docs][apn-docs].

Here's the basic one you're familiar with:
```json
{
    "aps" : { "alert" : "Message received from Bob" },
    "acme2" : [ "bang",  "whiz" ]
}
```

But these are also valid:
```json
{
    "aps" : {
        "alert" : {
            "title" : "Game Request",
            "body" : "Bob wants to play poker",
            "action-loc-key" : "PLAY"
        },
        "badge" : 5
    },
    "acme1" : "bar",
    "acme2" : [ "bang",  "whiz" ]
}
```

One which uses localization strings:
```json
{
    "aps" : {
        "alert" : {
            "loc-key" : "GAME_PLAY_REQUEST_FORMAT",
            "loc-args" : [ "Jenna", "Frank"]
        },
        "sound" : "chime.aiff"
    },
    "acme" : "foo"
}
```

Since `alert` simply gets serialized and passed through, you can set `alert` to any valid hash. For example, this example modified from the readme sets a title and body:

```ruby
notification = Houston::Notification.new(device: token)
notification.alert = {title: 'Hello', body: 'World!'}
APN.push(notification) # works!
``` 

[apn-docs]: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW1

**Comment by dankimio** [comment]
Providing helpers for [alert keys](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943365) is something we could implement in this gem.
