### ISSUE TITLE
iOS 13 requires new headers to the APNS

### ISSUE THREAD

**Issue by RebMeir** [nomad/houston#170]
Hey all!
The new iOS 13 requires some new headers in the APNS so the pushes will work
`apns-push-type` & `apns-priority`
Otherwise the pushes won't work for iOS 13 + os

**Comment by ab320012** [comment]
hm i have an issue for this already #168 and a PR albeit broken

**Comment by nightpool** [comment]
It looks like Houston currently uses the legacy, binary notification format instead of the HTTP/2 api. Apple so far has not provided any documentation on how to supply this parameter with the legacy notification, or if one is even required. Has someone been able to test that pushes through Houston are actually rejected from an iOS 13 device, or are we just going off of possibly inaccurate documentation?

**Comment by monochrome-particles** [comment]
I can confirm rejections from iOS 13 devices. Houston reports a successful send, but the push notification never reaches the device.

**Comment by monochrome-particles** [comment]
If you noticed that some messages are not getting received by the device, check your payload. Chances are, the payload does not include an `alert` parameter -- probably because you meant to send it as a 'background' message, like updating the badge, or signalling.

A workaround for this is to send a payload with some `alert` text (try an empty string), and the message will be received by the iOS 13 device.
