### ISSUE TITLE
APNs will no longer support the legacy binary protocol as of November 2020

### ISSUE THREAD

**Issue by toineheuvelmans** [nomad/houston#171]
If I understand correctly, Houston [still uses the binary protocol](https://github.com/nomad/houston/issues/170#issuecomment-536622006) instead of HTTP/2. [Apple announced](https://developer.apple.com/news/?id=11042019a) it will stop supporting this protocol as of November 2020. 
Are there any plans for updating Houston to using the HTTP/2-based APNs provider API?

**Comment by jmajonis** [comment]
Does this mean Houston, if not updated, will be unable to send push notifications when Apple stops supporting the protocol in November 2020?

**Comment by toineheuvelmans** [comment]
@jmajonis that is my assumption, yes. @mattt / @dankimio can you give us something, even if it is a statement that Houston won't be developed further?

**Comment by mattt** [comment]
@toineheuvelmans Sorry for the radio silence. I'm no longer the maintainer of this project, but I'm asking around to get a consensus about what the plans are going forward. That may be a new version using the new HTTP/2 API, or archiving the project and pointing folks to another library. Because time is of the essence, I'd hope for this decision to be made sooner rather than later (ideally by the end of next month).

**Comment by toineheuvelmans** [comment]
Thanks @mattt, 🤞

**Comment by GitBulk** [comment]
Hi, is there any update ?

**Comment by mattt** [comment]
Update: I've discussed this with @dankimio, and he indicated that he may have availability this month.

**Comment by toineheuvelmans** [comment]
@dankimio Can you give an update?

**Comment by jwhiting** [comment]
As the deadline for the protocol change is now right around the corner (~1 month) it seems time to look for other solutions - unless any contributors could come to the rescue at this point?

**Comment by mgornick** [comment]
@jwhiting Thus far, we have had a good experience with the Apnotic gem. It uses the latest HTTP/2 protocol, was simple to implement, and remained fairly lean versus some of the other options we evaluated.

See https://github.com/ostinelli/apnotic

While the Houston gem has been great over the years, the imposing deadline forced us to look at other options. Hope this helps other teams!

**Comment by fahad86** [comment]
Deadline pushed to March 2021, but sooner the change is implemented, the better:
https://developer.apple.com/news/?id=c88acm2b


FYI: https://www.pubnub.com/docs/platform/messages/push/apns2-migration-guide

**Comment by mattt** [comment]
Hey everyone. I sincerely apologize for my failure to communicate timely about the state of this project. At this point, I've decided to archive Houston, along with the rest of the projects in this org. Anyone who's still using Houston is encouraged to migrate to an alternative as soon as possible to support the APNs2. In the case of Houston, @mgornick's recommendation of [Apnotic](https://github.com/ostinelli/apnotic) looks like a good option.

For some additional context: I handed off Houston and the rest of the Nomad repos in 2015, and haven't had an occasion to use or work on them since. My only involvement has been occasionally having notifications come up in my feed, which brought me to this issue last March (https://github.com/nomad/houston/issues/171#issuecomment-602903317). Unfortunately, I was unable to secure a commitment from the current maintainer to resolve this issue. Given the timely nature of this issue, I decided that the best option would be to step in and archive the project.

Again, I apologize for any inconvenience I caused by not addressing this issue sooner. Thank you for your patience and understanding.
